2025-04-19 20:02:35,646 - INFO - Number of classes: 15
2025-04-19 20:02:35,646 - INFO - Training set size: 2985
2025-04-19 20:02:35,657 - INFO - Using Apple Silicon GPU (MPS)
2025-04-19 20:02:38,439 - INFO - ConvNeXt Large model selected
2025-04-19 20:02:38,611 - INFO - Starting training loop
[34m[1mwandb[0m: [33mWARNING[0m Fatal error while uploading data. Some run data will not be synced, but it will still be written to disk. Use `wandb sync` at the end of the run to try uploading.
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x10c7977e0>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/multiprocessing/connection.py", line 1136, in wait
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
Traceback (most recent call last):
  File "/Users/Charly_1/Desktop/MASTER/2ยบ Cuatri y anuales/ML II/5 - Deep Learning/idealistAI/models_generator/train_models.py", line 322, in <module>
    main()
  File "/Users/Charly_1/Desktop/MASTER/2ยบ Cuatri y anuales/ML II/5 - Deep Learning/idealistAI/models_generator/train_models.py", line 310, in main
    train(
  File "/Users/Charly_1/Desktop/MASTER/2ยบ Cuatri y anuales/ML II/5 - Deep Learning/idealistAI/models_generator/train_models.py", line 209, in train
    optimizer.step()
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/torch/optim/adam.py", line 166, in step
    adam(
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/torch/optim/adam.py", line 316, in adam
    func(params,
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/torch/optim/adam.py", line 439, in _single_tensor_adam
    denom = (exp_avg_sq.sqrt() / bias_correction2_sqrt).add_(eps)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x141a807c0>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/opt/miniconda3/envs/dl_lab/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
